<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="KooliProjekt.*\/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="KooliProjekt.Application\KooliProjekt.Application.csproj" />
  </ItemGroup>

</Project>
